// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ncopdvferthqzftnlaau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jb3BkdmZlcnRocXpmdG5sYWF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4ODcyMzIsImV4cCI6MjA1ODQ2MzIzMn0.C4hq_PpX6mr_jyqnvsvIGNHeti7Thw_pR_ymiQa5iNs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);